name: RED CREATIVE FILM
favicon: null
layout_spectrum: 0.74265
typography_spectrum: 0.4752372861839831
title: This is a test for a new web site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#bbbbbb'
    - '#5f5f5f'
    - '#828282'
  brandStrength: 0.0616707808803767
  lightness: 0.8597058656159788
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
