name: RED CREATIVE FILM
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4752372861839831
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#d9c8aa'
    - '#a39274'
    - '#473c29'
    - '#fff8ff'
  brandStrength: 0.0616707808803767
  lightness: 0.8597058656159788
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
